### ISSUE TITLE
Apparently wrong version downloads from releases v.2.14

### ISSUE THREAD

**Issue by morkeltry** [AvaProtocol/OAK-blockchain#518]
[Releases 2.14](https://github.com/OAK-Foundation/OAK-blockchain/releases/tag/v2.1.4) binary and source code downloads apparently provide v.2.1.0-e07a5345066.

**Steps to Reproduce**

```
wget https://github.com/OAK-Foundation/OAK-blockchain/releases/download/v2.0.0/oak-collator
chmod +755 oak-collator
./oak-collator --version
```
> `oak-collator 2.1.0-e07a5345066`

Calling `system::version()` extrinsic through https://polkadot.js.org/apps returns:
> 2.1.0-e07a5345066

*OR*

```
git clone https://github.com/OAK-Foundation/OAK-blockchain.git
cargo build --release --features turing-node --features dev-queue
./target/release/oak-collator --version
```
> `oak-collator 2.1.0-e07a5345066`

and running Moonbeam EVM smart contract automation [demo](https://github.com/OAK-Foundation/xcm-demo/tree/master#moonbeam-evm-smart-contract-automation) chokes on `Error: The scheduleAs parameter should not be empty`, which  [should not be present](https://github.com/OAK-Foundation/OAK-blockchain/pull/499) in v.2.1.4

**Expected vs. Actual Behavior**

`oak-collator` to report as, and operate as, v.2.1.4
vs
reports as  `oak-collator 2.1.0-e07a5345066` and  does not include merged feature of v.2.1.4

**Related issue**
[ Moonbeam demo cannot work with required Turing version](https://github.com/OAK-Foundation/xcm-demo/issues/113)

**Comment by chrisli30** [comment]
@morkeltry thanks for your report and I apologize for the product experience you've had. We will investigate the issue today and get back to you shortly!

**Comment by chrisli30** [comment]
@morkeltry, the binary version `oak-collator 2.1.0-e07a5345066` is **correct and by design**. Because the node client has not changed since 2.1.0, as you can view from the history of [Releases](https://github.com/OAK-Foundation/OAK-blockchain/releases), the binary filename still starts with `2.1.0`. From v2.1.0 to v2.1.4, only blockchain runtime were updated, and there’s no requirement for node operator to update the `oak-collator` binary file.

Please let me know if that makes sense and there are more questions.
